spring.application.name=demo

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:productdb
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

jwt.secret=nuZWTW+TQbbeOjF8gkoSEkP4cWIm+j8hlWiHWYCIpIU=
jwt.expiration=3600000